#!/bin/bash

HEADER="/* ************************************************************************** */
/*                                                                            */
/*                                                       :::      ::::::::    */
/*   test.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: flinguen <florent@linguenheld.net>          +#+  +:+       +#+       */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: $(date '+%Y/%m/%d %H:%M:%S') by flinguen          #+#    #+#             */
/*   Updated: $(date '+%Y/%m/%d %H:%M:%S') by flinguen         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */"


TOPBOT="/* ************************************************************************** */"
MIDDLE="/*                                                +#+#+#+#+#+   +#+           */"

    echo "$HEADER" > test.h

FILES="$(find . | grep -E '(\.c$)|(\.h$)')"

ME="flinguen"
NEW_DATE=$(date '+%Y/%m/%d %H:%M:%S')
# echo "$FILES"


find . | grep -E '(\.c$)|(\.h$)' | while read F; do

  FOUR="/*                                                      :+:      :+:    :+:   */"
  FILE_NAME="/*   ${F##*/}"
  START=$(($(echo "$FILE_NAME" | wc -m) - 80))
  FOUR="${FILE_NAME}${FOUR:($START)}"

  # echo "------------------> $START"
  # echo "${FILE_NAME}${FOUR:($START)}"
  echo "deal with: $F"

  # Empty file
  if [[ -s "$F" ]]; then
    echo "$HEADER" > "$F"
  fi

  # Existing header
  DONE=""
  if [[ $(sed -n -e 1p "$F") == "${TOPBOT}" ]]; then
    if [[ $(sed -n -e 7p "$F") == "${MIDDLE}" ]]; then
      if [[ $(sed -n -e 11p "$F") == "${TOPBOT}" ]]; then

        echo " $F is OK"
        # File name -----------------------------------------
        NAME_LINE=$(sed '4q;d' ${F})
        echo "$NAME_LINE" | cat -e

        # Update --------------------------------------------
        UPDATE_LINE=$(sed '9q;d' ${F})

        TO_UP=$(echo ${UPDATE_LINE:14:20})
        WHO=$(echo "$UPDATE_LINE" | awk '{print $6}')

        # echo "$WHO" | cat -e
        # echo "$TO_UP" | cat -e
        sed -i "9s%${TO_UP}%${NEW_DATE}%"  "$F"
        sed -i "9s%${WHO}%${ME}%"  "$F"

        DONE="TRUE"
      fi
    fi
  fi

  # No header
  if [[ -z "$DONE" ]]; then
    echo "Empty file does that $F"
    sed -i "1i ${ONE}" "$F"
  fi





  # head -n 11 $F | tail -n 1 | sed "s/[^\*]//g" | cat -e
  # head -n 11 $F | tail -n 1 | sed "s/" | wc -m

done

